// Model structs and TryFrom<&Row> impls generated by quiver-codegen.
// Wrapper functions at the bottom provide DomainError-returning API for services.

use serde::{Deserialize, Serialize};
use quiver_driver_core::{Row, RowError};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Component {
    pub id: i32,
    pub name: String,
    pub description: String,
    pub parent_id: Option<i32>,
    pub expanded_access_enabled: bool,
    pub editable_comments_enabled: bool,
    pub created_at: String,
    pub updated_at: String,
}

impl TryFrom<&Row> for Component {
    type Error = RowError;

    fn try_from(row: &Row) -> Result<Self, Self::Error> {
        Ok(Self {
            id: row.int32("id")?,
            name: row.text("name")?,
            description: row.text("description")?,
            parent_id: row.optional_int32("parentId")?,
            expanded_access_enabled: row.boolean("expandedAccessEnabled")?,
            editable_comments_enabled: row.boolean("editableCommentsEnabled")?,
            created_at: row.text("createdAt")?,
            updated_at: row.text("updatedAt")?,
        })
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComponentCreateInput {
    pub name: String,
    pub description: Option<String>,
    pub parent_id: Option<i32>,
    pub expanded_access_enabled: Option<bool>,
    pub editable_comments_enabled: Option<bool>,
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ComponentUpdateInput {
    pub name: Option<String>,
    pub description: Option<String>,
    pub parent_id: Option<i32>,
    pub expanded_access_enabled: Option<bool>,
    pub editable_comments_enabled: Option<bool>,
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ComponentAcl {
    pub id: i32,
    pub component_id: i32,
    pub identity_type: String,
    pub identity_value: String,
    pub permissions: String,
    pub created_at: String,
}

impl TryFrom<&Row> for ComponentAcl {
    type Error = RowError;

    fn try_from(row: &Row) -> Result<Self, Self::Error> {
        Ok(Self {
            id: row.int32("id")?,
            component_id: row.int32("componentId")?,
            identity_type: row.text("identityType")?,
            identity_value: row.text("identityValue")?,
            permissions: row.text("permissions")?,
            created_at: row.text("createdAt")?,
        })
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComponentAclCreateInput {
    pub component_id: i32,
    pub identity_type: String,
    pub identity_value: String,
    pub permissions: String,
    pub created_at: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ComponentAclUpdateInput {
    pub component_id: Option<i32>,
    pub identity_type: Option<String>,
    pub identity_value: Option<String>,
    pub permissions: Option<String>,
    pub created_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Issue {
    pub id: i32,
    pub title: String,
    pub description: String,
    pub status: String,
    pub priority: String,
    pub severity: String,
    pub issue_type: String,
    pub component_id: i32,
    pub assignee: String,
    pub reporter: String,
    pub verifier: String,
    pub found_in: String,
    pub targeted_to: String,
    pub verified_in: String,
    pub in_prod: bool,
    pub archived: bool,
    pub access_level: String,
    pub vote_count: i32,
    pub duplicate_count: i32,
    pub created_at: String,
    pub modified_at: String,
    pub resolved_at: Option<String>,
    pub verified_at: Option<String>,
    pub duplicate_of_id: Option<i32>,
}

impl TryFrom<&Row> for Issue {
    type Error = RowError;

    fn try_from(row: &Row) -> Result<Self, Self::Error> {
        Ok(Self {
            id: row.int32("id")?,
            title: row.text("title")?,
            description: row.text("description")?,
            status: row.text("status")?,
            priority: row.text("priority")?,
            severity: row.text("severity")?,
            issue_type: row.text("issueType")?,
            component_id: row.int32("componentId")?,
            assignee: row.text("assignee")?,
            reporter: row.text("reporter")?,
            verifier: row.text("verifier")?,
            found_in: row.text("foundIn")?,
            targeted_to: row.text("targetedTo")?,
            verified_in: row.text("verifiedIn")?,
            in_prod: row.boolean("inProd")?,
            archived: row.boolean("archived")?,
            access_level: row.text("accessLevel")?,
            vote_count: row.int32("voteCount")?,
            duplicate_count: row.int32("duplicateCount")?,
            created_at: row.text("createdAt")?,
            modified_at: row.text("modifiedAt")?,
            resolved_at: row.optional_text("resolvedAt")?,
            verified_at: row.optional_text("verifiedAt")?,
            duplicate_of_id: row.optional_int32("duplicateOfId")?,
        })
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IssueCreateInput {
    pub title: String,
    pub description: Option<String>,
    pub status: Option<String>,
    pub priority: Option<String>,
    pub severity: Option<String>,
    pub issue_type: Option<String>,
    pub component_id: i32,
    pub assignee: Option<String>,
    pub reporter: Option<String>,
    pub verifier: Option<String>,
    pub found_in: Option<String>,
    pub targeted_to: Option<String>,
    pub verified_in: Option<String>,
    pub in_prod: Option<bool>,
    pub archived: Option<bool>,
    pub access_level: Option<String>,
    pub vote_count: Option<i32>,
    pub duplicate_count: Option<i32>,
    pub created_at: Option<String>,
    pub modified_at: Option<String>,
    pub resolved_at: Option<String>,
    pub verified_at: Option<String>,
    pub duplicate_of_id: Option<i32>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct IssueUpdateInput {
    pub title: Option<String>,
    pub description: Option<String>,
    pub status: Option<String>,
    pub priority: Option<String>,
    pub severity: Option<String>,
    pub issue_type: Option<String>,
    pub component_id: Option<i32>,
    pub assignee: Option<String>,
    pub reporter: Option<String>,
    pub verifier: Option<String>,
    pub found_in: Option<String>,
    pub targeted_to: Option<String>,
    pub verified_in: Option<String>,
    pub in_prod: Option<bool>,
    pub archived: Option<bool>,
    pub access_level: Option<String>,
    pub vote_count: Option<i32>,
    pub duplicate_count: Option<i32>,
    pub created_at: Option<String>,
    pub modified_at: Option<String>,
    pub resolved_at: Option<String>,
    pub verified_at: Option<String>,
    pub duplicate_of_id: Option<i32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IssueParent {
    pub id: i32,
    pub child_id: i32,
    pub parent_id: i32,
}

impl TryFrom<&Row> for IssueParent {
    type Error = RowError;

    fn try_from(row: &Row) -> Result<Self, Self::Error> {
        Ok(Self {
            id: row.int32("id")?,
            child_id: row.int32("childId")?,
            parent_id: row.int32("parentId")?,
        })
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IssueParentCreateInput {
    pub child_id: i32,
    pub parent_id: i32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct IssueParentUpdateInput {
    pub child_id: Option<i32>,
    pub parent_id: Option<i32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IssueBlocking {
    pub id: i32,
    pub blocking_id: i32,
    pub blocked_id: i32,
}

impl TryFrom<&Row> for IssueBlocking {
    type Error = RowError;

    fn try_from(row: &Row) -> Result<Self, Self::Error> {
        Ok(Self {
            id: row.int32("id")?,
            blocking_id: row.int32("blockingId")?,
            blocked_id: row.int32("blockedId")?,
        })
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IssueBlockingCreateInput {
    pub blocking_id: i32,
    pub blocked_id: i32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct IssueBlockingUpdateInput {
    pub blocking_id: Option<i32>,
    pub blocked_id: Option<i32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Comment {
    pub id: i32,
    pub issue_id: i32,
    pub author: String,
    pub body: String,
    pub is_description: bool,
    pub hidden: bool,
    pub hidden_by: Option<String>,
    pub hidden_at: Option<String>,
    pub created_at: String,
    pub modified_at: Option<String>,
}

impl TryFrom<&Row> for Comment {
    type Error = RowError;

    fn try_from(row: &Row) -> Result<Self, Self::Error> {
        Ok(Self {
            id: row.int32("id")?,
            issue_id: row.int32("issueId")?,
            author: row.text("author")?,
            body: row.text("body")?,
            is_description: row.boolean("isDescription")?,
            hidden: row.boolean("hidden")?,
            hidden_by: row.optional_text("hiddenBy")?,
            hidden_at: row.optional_text("hiddenAt")?,
            created_at: row.text("createdAt")?,
            modified_at: row.optional_text("modifiedAt")?,
        })
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommentCreateInput {
    pub issue_id: i32,
    pub author: String,
    pub body: String,
    pub is_description: Option<bool>,
    pub hidden: Option<bool>,
    pub hidden_by: Option<String>,
    pub hidden_at: Option<String>,
    pub created_at: Option<String>,
    pub modified_at: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CommentUpdateInput {
    pub issue_id: Option<i32>,
    pub author: Option<String>,
    pub body: Option<String>,
    pub is_description: Option<bool>,
    pub hidden: Option<bool>,
    pub hidden_by: Option<String>,
    pub hidden_at: Option<String>,
    pub created_at: Option<String>,
    pub modified_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CommentRevision {
    pub id: i32,
    pub comment_id: i32,
    pub body: String,
    pub edited_by: String,
    pub created_at: String,
}

impl TryFrom<&Row> for CommentRevision {
    type Error = RowError;

    fn try_from(row: &Row) -> Result<Self, Self::Error> {
        Ok(Self {
            id: row.int32("id")?,
            comment_id: row.int32("commentId")?,
            body: row.text("body")?,
            edited_by: row.text("editedBy")?,
            created_at: row.text("createdAt")?,
        })
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommentRevisionCreateInput {
    pub comment_id: i32,
    pub body: String,
    pub edited_by: String,
    pub created_at: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CommentRevisionUpdateInput {
    pub comment_id: Option<i32>,
    pub body: Option<String>,
    pub edited_by: Option<String>,
    pub created_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Hotlist {
    pub id: i32,
    pub name: String,
    pub description: String,
    pub owner: String,
    pub archived: bool,
    pub created_at: String,
    pub modified_at: String,
}

impl TryFrom<&Row> for Hotlist {
    type Error = RowError;

    fn try_from(row: &Row) -> Result<Self, Self::Error> {
        Ok(Self {
            id: row.int32("id")?,
            name: row.text("name")?,
            description: row.text("description")?,
            owner: row.text("owner")?,
            archived: row.boolean("archived")?,
            created_at: row.text("createdAt")?,
            modified_at: row.text("modifiedAt")?,
        })
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HotlistCreateInput {
    pub name: String,
    pub description: Option<String>,
    pub owner: Option<String>,
    pub archived: Option<bool>,
    pub created_at: Option<String>,
    pub modified_at: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct HotlistUpdateInput {
    pub name: Option<String>,
    pub description: Option<String>,
    pub owner: Option<String>,
    pub archived: Option<bool>,
    pub created_at: Option<String>,
    pub modified_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HotlistAcl {
    pub id: i32,
    pub hotlist_id: i32,
    pub identity_type: String,
    pub identity_value: String,
    pub permission: String,
    pub created_at: String,
}

impl TryFrom<&Row> for HotlistAcl {
    type Error = RowError;

    fn try_from(row: &Row) -> Result<Self, Self::Error> {
        Ok(Self {
            id: row.int32("id")?,
            hotlist_id: row.int32("hotlistId")?,
            identity_type: row.text("identityType")?,
            identity_value: row.text("identityValue")?,
            permission: row.text("permission")?,
            created_at: row.text("createdAt")?,
        })
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HotlistAclCreateInput {
    pub hotlist_id: i32,
    pub identity_type: String,
    pub identity_value: String,
    pub permission: String,
    pub created_at: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct HotlistAclUpdateInput {
    pub hotlist_id: Option<i32>,
    pub identity_type: Option<String>,
    pub identity_value: Option<String>,
    pub permission: Option<String>,
    pub created_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HotlistIssue {
    pub id: i32,
    pub hotlist_id: i32,
    pub issue_id: i32,
    pub position: i32,
    pub added_at: String,
    pub added_by: String,
}

impl TryFrom<&Row> for HotlistIssue {
    type Error = RowError;

    fn try_from(row: &Row) -> Result<Self, Self::Error> {
        Ok(Self {
            id: row.int32("id")?,
            hotlist_id: row.int32("hotlistId")?,
            issue_id: row.int32("issueId")?,
            position: row.int32("position")?,
            added_at: row.text("addedAt")?,
            added_by: row.text("addedBy")?,
        })
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HotlistIssueCreateInput {
    pub hotlist_id: i32,
    pub issue_id: i32,
    pub position: Option<i32>,
    pub added_at: Option<String>,
    pub added_by: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct HotlistIssueUpdateInput {
    pub hotlist_id: Option<i32>,
    pub issue_id: Option<i32>,
    pub position: Option<i32>,
    pub added_at: Option<String>,
    pub added_by: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EventLog {
    pub id: i32,
    pub event_time: String,
    pub event_type: String,
    pub actor: String,
    pub entity_type: String,
    pub entity_id: i32,
    pub payload: String,
}

impl TryFrom<&Row> for EventLog {
    type Error = RowError;

    fn try_from(row: &Row) -> Result<Self, Self::Error> {
        Ok(Self {
            id: row.int32("id")?,
            event_time: row.text("eventTime")?,
            event_type: row.text("eventType")?,
            actor: row.text("actor")?,
            entity_type: row.text("entityType")?,
            entity_id: row.int32("entityId")?,
            payload: row.text("payload")?,
        })
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventLogCreateInput {
    pub event_time: Option<String>,
    pub event_type: String,
    pub actor: String,
    pub entity_type: String,
    pub entity_id: i32,
    pub payload: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EventLogUpdateInput {
    pub event_time: Option<String>,
    pub event_type: Option<String>,
    pub actor: Option<String>,
    pub entity_type: Option<String>,
    pub entity_id: Option<i32>,
    pub payload: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Group {
    pub id: i32,
    pub name: String,
    pub display_name: String,
    pub description: String,
    pub creator: String,
    pub created_at: String,
    pub updated_at: String,
}

impl TryFrom<&Row> for Group {
    type Error = RowError;

    fn try_from(row: &Row) -> Result<Self, Self::Error> {
        Ok(Self {
            id: row.int32("id")?,
            name: row.text("name")?,
            display_name: row.text("displayName")?,
            description: row.text("description")?,
            creator: row.text("creator")?,
            created_at: row.text("createdAt")?,
            updated_at: row.text("updatedAt")?,
        })
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GroupCreateInput {
    pub name: String,
    pub display_name: Option<String>,
    pub description: Option<String>,
    pub creator: String,
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GroupUpdateInput {
    pub name: Option<String>,
    pub display_name: Option<String>,
    pub description: Option<String>,
    pub creator: Option<String>,
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GroupMember {
    pub id: i32,
    pub group_id: i32,
    pub member_type: String,
    pub member_value: String,
    pub role: String,
    pub added_by: String,
    pub created_at: String,
}

impl TryFrom<&Row> for GroupMember {
    type Error = RowError;

    fn try_from(row: &Row) -> Result<Self, Self::Error> {
        Ok(Self {
            id: row.int32("id")?,
            group_id: row.int32("groupId")?,
            member_type: row.text("memberType")?,
            member_value: row.text("memberValue")?,
            role: row.text("role")?,
            added_by: row.text("addedBy")?,
            created_at: row.text("createdAt")?,
        })
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GroupMemberCreateInput {
    pub group_id: i32,
    pub member_type: String,
    pub member_value: String,
    pub role: Option<String>,
    pub added_by: Option<String>,
    pub created_at: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GroupMemberUpdateInput {
    pub group_id: Option<i32>,
    pub member_type: Option<String>,
    pub member_value: Option<String>,
    pub role: Option<String>,
    pub added_by: Option<String>,
    pub created_at: Option<String>,
}


