use super::{step, step_assert, step_fail, Pipeline};

pub fn pipeline() -> Pipeline {
    Pipeline {
        name: "security",
        summary: "Demonstrate auth enforcement, ACL bootstrapping, and impersonation prevention",
        steps: vec![
            // --- Setup ---
            step_assert(
                "Create component as admin",
                &[
                    "--user",
                    "admin@demo.com",
                    "component",
                    "create",
                    "Confidential",
                    "--description",
                    "Restricted component",
                ],
                &["Confidential"],
            ),
            step(
                "Bootstrap ACL: admin grants themselves ADMIN_COMPONENTS",
                &[
                    "--user",
                    "admin@demo.com",
                    "acl",
                    "set-component",
                    "1",
                    "--identity-type",
                    "user",
                    "--identity-value",
                    "admin@demo.com",
                    "--permissions",
                    "ADMIN_COMPONENTS",
                ],
            ),
            // --- Unauthenticated access denied ---
            step_fail(
                "Unauthenticated: cannot set ACL",
                &[
                    "acl",
                    "set-component",
                    "1",
                    "--identity-type",
                    "user",
                    "--identity-value",
                    "evil@hack.com",
                    "--permissions",
                    "ADMIN_COMPONENTS",
                ],
            ),
            step_fail(
                "Unauthenticated: cannot view ACL",
                &["acl", "get-component", "1"],
            ),
            step_fail(
                "Unauthenticated: cannot check permissions",
                &["acl", "check", "1", "--user", "admin@demo.com"],
            ),
            step_fail(
                "Unauthenticated: cannot create hotlist",
                &[
                    "hotlist",
                    "create",
                    "--name",
                    "Hijacked Hotlist",
                    "--owner",
                    "attacker@hack.com",
                ],
            ),
            // --- Non-admin cannot escalate ---
            step(
                "Grant viewer VIEW_ISSUES only",
                &[
                    "--user",
                    "admin@demo.com",
                    "acl",
                    "set-component",
                    "1",
                    "--identity-type",
                    "user",
                    "--identity-value",
                    "viewer@demo.com",
                    "--permissions",
                    "VIEW_ISSUES",
                ],
            ),
            step_fail(
                "Viewer cannot escalate to admin",
                &[
                    "--user",
                    "viewer@demo.com",
                    "acl",
                    "set-component",
                    "1",
                    "--identity-type",
                    "user",
                    "--identity-value",
                    "viewer@demo.com",
                    "--permissions",
                    "ADMIN_COMPONENTS",
                ],
            ),
            step_fail(
                "Viewer cannot view ACL entries",
                &["--user", "viewer@demo.com", "acl", "get-component", "1"],
            ),
            // --- Hotlist owner impersonation prevented ---
            step_assert(
                "Create hotlist: owner field is overridden to authenticated user",
                &[
                    "--user",
                    "admin@demo.com",
                    "hotlist",
                    "create",
                    "--name",
                    "Sprint 1",
                    "--owner",
                    "someone_else@demo.com",
                ],
                &["Sprint 1", "admin@demo.com"],
            ),
            step_assert(
                "Creator auto-gets HOTLIST_ADMIN (can view ACL)",
                &["--user", "admin@demo.com", "acl", "get-hotlist", "1"],
                &["admin@demo.com", "HOTLIST_ADMIN"],
            ),
            step_fail(
                "Non-admin cannot modify hotlist ACL",
                &[
                    "--user",
                    "viewer@demo.com",
                    "acl",
                    "set-hotlist",
                    "1",
                    "--identity-type",
                    "user",
                    "--identity-value",
                    "viewer@demo.com",
                    "--permission",
                    "HOTLIST_ADMIN",
                ],
            ),
            // --- Permission enforcement on issues ---
            step(
                "Grant dev CREATE_ISSUES + VIEW_ISSUES",
                &[
                    "--user",
                    "admin@demo.com",
                    "acl",
                    "set-component",
                    "1",
                    "--identity-type",
                    "user",
                    "--identity-value",
                    "dev@demo.com",
                    "--permissions",
                    "CREATE_ISSUES,VIEW_ISSUES",
                ],
            ),
            step_assert(
                "Dev can create an issue",
                &[
                    "--user",
                    "dev@demo.com",
                    "issue",
                    "create",
                    "-c",
                    "1",
                    "-t",
                    "Fix critical vulnerability",
                    "-p",
                    "P0",
                    "--type",
                    "BUG",
                ],
                &["Fix critical vulnerability"],
            ),
            step_fail(
                "Viewer cannot create issues",
                &[
                    "--user",
                    "viewer@demo.com",
                    "issue",
                    "create",
                    "-c",
                    "1",
                    "-t",
                    "Should be denied",
                    "-p",
                    "P2",
                    "--type",
                    "BUG",
                ],
            ),
            // --- Admin can inspect permissions ---
            step_assert(
                "Admin checks dev's effective permissions",
                &[
                    "--user",
                    "admin@demo.com",
                    "acl",
                    "check",
                    "1",
                    "--user",
                    "dev@demo.com",
                ],
                &["CREATE_ISSUES", "VIEW_ISSUES"],
            ),
            step_assert(
                "Admin checks viewer's effective permissions",
                &[
                    "--user",
                    "admin@demo.com",
                    "acl",
                    "check",
                    "1",
                    "--user",
                    "viewer@demo.com",
                ],
                &["VIEW_ISSUES"],
            ),
            // --- Cleanup: remove viewer ACL ---
            step(
                "Remove viewer's ACL entry",
                &[
                    "--user",
                    "admin@demo.com",
                    "acl",
                    "remove-component",
                    "1",
                    "--identity-type",
                    "user",
                    "--identity-value",
                    "viewer@demo.com",
                ],
            ),
        ],
    }
}
